### ISSUE TITLE
Integrating with sm admin menu

### ISSUE THREAD

**Issue by EBS-DarkD** [AzumiNeko/Insurgency#1]
I'm trying to get this to work with the sm_admin menu and have been able to create an entry that calls this cvar (we have a huge number of maps). Trouble is it does nothing.

I'm using the following in the adminmenu_custom.txt

"Commands"
{
    "Map Commands"
    {
      "Our Maps"
      {
         "cmd"        "sm_cmap #1"
         "execute"    "server"
         "admin"      "sm_slay"
         "1"
         {
            "title"        "Maps:"
            "type"         "mapcycle"
            "path"         "mapcycle_ebs.txt"
         }
      }
    }
}

I get a menu item but all that happens when I click it is sm_admin closes! Any clues if it's possible to get this to work this way?

**Comment by zDestinate** [comment]
I'm not familiar with sm_admin menu so I can't really help.
